### ISSUE TITLE
Double definition of esp_core_dump_image_erase

### ISSUE THREAD

**Issue by duwuwansch** [MathieuDeprez/ESP32_CoreDump_Arduino_1.0.6#6]
In the example src the function: esp_core_dump_image_erase is defined. But it also includes esp_core_dump.h which also defines the same function. As a result ld.exe complains during build:  multiple definition of `esp_core_dump_image_erase';

**Comment by MathieuDeprez** [comment]
Hi,
esp_core_dump_image_erase() is defined for the version after Arduino 1.0.6. I just copied it to use it in the old 1.0.6 version.
Are you sure that you are using Arduino 1.0.6?

**Comment by duwuwansch** [comment]
Oh sorry, did overlook this. I'm using 1.8 and not 1.0.6.
So just commenting this function will do the trick?

**Comment by MathieuDeprez** [comment]
I don't think there is a 1.8 version. I am talking about the **arduino-esp32** version (https://github.com/espressif/arduino-esp32/releases).
After the 1.0.6 version, there are the 2.0.0, 2.0.1, 2.0.2 and 2.0.3 version.

Here is my repository that allows you to use the esp_core_dump functionnality with the 2.0.2 version : https://github.com/MathieuDeprez/ESP32_CoreDump_Arduino_2.0.2

**Comment by duwuwansch** [comment]
Hi Matthieu, (tu es francais?)

thank you for your response and the link. In fact I use 2.0.2.

But I'm having issues understanding your project. Currently my struggle
is about setting the right flags in sdkconfig which I need for the dump
to flash feature.
- Using menuconfig does not work as im using arduino and not espidf.
Both dont work togehter -> see:
https://community.platformio.org/t/right-way-for-custom-sdkconfig-per-environment/27546/4

- I saw that you tried to set the flags in your platformio.ini. But
since they are commented, I assume this did not work

[env:esp32dev]
platform =
https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
board = esp32dev
framework=arduino
platform_packages =
     platformio/toolchain-xtensa32@^2.50200.97
     platformio/framework-arduinoespressif32 @
https://github.com/espressif/arduino-esp32.git#2.0.2
     platformio/tool-esptoolpy@^1.30100.210531
lib_deps = arduino-libraries/Arduino_JSON@^0.1.0
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;board_build.partitions = Tom16MBmin_spiffs.csv
build_flags =
; -DCONFIG_ESP_COREDUMP_ENABLE=y
; -DCONFIG_ESP_COREDUMP_ENABLE_TO_FLASH=y
; -DCONFIG_ESP_COREDUMP_DATA_FORMAT_ELF=y
; -DCORE_DEBUG_LEVEL=4
; -DCONFIG_ESP_COREDUMP_MAX_TASKS_NUM=64
; -DCONFIG_ESP_COREDUMP_CHECKSUM_CRC32=y
;build_unflags = DCONFIG_ESP_COREDUMP_ENABLE_TO_NONE=y


- So did you do the edits directly in the sdkconfig in the out.zip?
Wouldnt that overwrite the complete setting for all projects?

- Why are you using the platform_packages =
     platformio/framework-arduinoespressif32 @
https://github.com/espressif/arduino-esp32.git#2.0.2

Would the standard platformio not use 2.0.2 as standard. Why explicitly
stating it here?


- I could not find a source file in your latest git. Did I oversee it?

Thank you for your help.
BR David

Am 05.05.2022 um 21:41 schrieb MathieuDeprez:

**Comment by MathieuDeprez** [comment]
Hi @duwuwansch, (Oui, je suis Français)

The thing is that the Arduino framework includes a version of ESP-IDF.
Arduino 1.0.6 is using ESP-IDF 3.5 and Arduino 2.0.2 is using ESP-IDF 4.4.

By default, platformIO uses Arduino 1.0.6 and we are waiting for the development team to integrate Arduino 2.0.0(at minimum). This following line allows you to use the Arduino 2.0.2 on PlatformIO :
`platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.2`
But it is not perfect, this is why you need to import other tools like:
```
platformio/toolchain-xtensa32@^2.50200.97
platformio/tool-esptoolpy@^1.30100.210531
```

You are right, you can't use menuconfig because you are not directly using the ESP-IDF framework.
This is why I made my repos **ESP32_CoreDump_Arduino_1.0.6** and **ESP32_CoreDump_Arduino_2.0.2**
This is was I have done:
- I installed ESP-IDF 3.5(for Arduino 1.0.6) and ESP-IDF 4.4(for Arduino 2.0.2).
- I ran "menuconfig" and enabled the dump to flash feature.
- I used this tool to generate the Arduino stuff from ESP-IDF : https://github.com/espressif/esp32-arduino-lib-builder

Finally, I have a custom Arduino SDK (in the out.zip file) that allows for the core dump feature.
You just have to replace the content that PlatformIO downloads by the content of that out.zip file and you are good to go!

* out.zip for Arduino 1.0.6
* out_IDF4.4Beta1.zip for Arduino 2.0.2
